services:
  - type: web
    name: cesium-demo
    runtime: static
    buildCommand: cd cesium_demo && npm ci && npm run build && cd .. && mkdir -p .cesium_demo && cp -R cesium_demo/dist .cesium_demo/dist
    staticPublishPath: .cesium_demo/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
